- name: Set up Ninja
      uses: Ninja-build/ninja-setup-action@v3

    - name: Install Qt
      uses: jurplel/install-qt-action@v3
      with:
        version: '6.8.0'
        host: 'windows'
        target: 'desktop'
        arch: 'win64_msvc2019_64'
        tools: 'tools_cmake'

    - name: Setup MSVC Environment
      uses: ilammy/msvc-dev-cmd@v1

    - name: Checkout Extra CMake Modules (ECM)
      uses: actions/checkout@v4
      with:
        repository: KDE/extra-cmake-modules
        path: ecm-src

    - name: Build and Install ECM Locally
      run: |
        cmake -S ecm-src -B ecm-build -DCMAKE_INSTALL_PREFIX="${{ github.workspace }}/ecm-install"
        cmake --build ecm-build --target install

    - name: Configure CMake
      run: |
        cmake -B build -G "Ninja" -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH="${{ github.workspace }}/ecm-install"

    - name: Build with CMake
      run: |
        cmake --build build --config Release

    - name: Upload Windows Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: PrismLauncher-Windows-Exe
        path: build/bin/
